sudo: required
services:
    - docker

before_install:
  - docker build -t eureka-server ./service-discovery
  - docker build -t config-server ./config-server
  - docker build -t book-service ./book-service
  - docker build -t author-service ./author-service
