language: java

sudo: required
services:
    - docker
    
after_sucess:
  - docker build -t eureka-server ./service-discovery
  - docker build -t config-server ./config-server
  - docker build -t book-service ./book-service
  - docker build -t author-service ./author-service
