version: '3'
services:
  eureka-server:
    container_name: eureka-server
    build:
      context: ./service-discovery/
      dockerfile: Dockerfile
    image: eureka-server
    ports:
      - "8761:8761"
    networks:
      - "config-network"
    environment:
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
      - EUREKA_HOST=eureka-server
      - EUREKA_PORT=8761

  config-server:
    container_name: config-server
    build:
      context: ./config-server/
      dockerfile: Dockerfile
    image: config-server
    ports:
      - "8888:8888"
    networks:
      - "config-network"
    environment:
      - CONFIG_SERVER_DEFAULT_PORT=8888
   # restart: on-failure
  
  book-service:
    container_name: book-service
    build:
      context: ./book-service/
      dockerfile: Dockerfile
    image: book-service
    depends_on:
      - config-server
      - eureka-server
    ports:
      - "8082:8082"
    networks:
      - "config-network"
    environment:
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_HOST=eureka-server
      - EUREKA_PORT=8761
    entrypoint: /app/book_service_entry_point.sh

  author-service:
    container_name: author-service
    build:
      context: ./author-service/
      dockerfile: Dockerfile
    image: author-service
    depends_on:
      - config-server
      - eureka-server
    ports:
      - "8081:8081"
    networks:
      - "config-network"
    environment:
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_HOST=eureka-server
      - EUREKA_PORT=8761
    entrypoint: /app/author_service_entry_point.sh

networks:
  config-network:
